# Generated by Django 2.0.10 on 2019-02-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0002_auto_20190225_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='is_limited',
            field=models.BooleanField(default=False, help_text='Limited circles can grow up to a fixed number of members.', verbose_name='limited'),
        ),
    ]
