# Generated by Django 2.0.10 on 2019-02-26 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_auto_20190226_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='remaining_invitation',
            new_name='remaining_invitations',
        ),
    ]
