# Generated by Django 2.0.10 on 2019-02-27 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0004_auto_20190226_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='userd_invitation',
            new_name='used_invitation',
        ),
    ]
