# Generated by Django 2.0.10 on 2019-02-27 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0005_auto_20190227_2238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='used_invitation',
            new_name='used_invitations',
        ),
    ]
